import {StyleSheet} from 'react-native';
import {width, moderateScale} from './scale';

//all inputs styles
export const inputStyles = StyleSheet.create({
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: width - 50,
    backgroundColor: '#F9FAFB',
    borderRadius: moderateScale(16),
    paddingHorizontal: moderateScale(10),
    borderColor: 'black',
  },
  QRInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: width - 50,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: moderateScale(16),
    paddingHorizontal: moderateScale(10),
    borderColor: 'white',
    borderWidth: 1,
  },
  oneNumInputContainer: {
    width: width - 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  focusedInputContainer: {
    borderWidth: 1,
  },
  input: {
    color: '#013335',
    fontSize: moderateScale(16),
    padding: moderateScale(10),
    flex: 1,
  },
  QRInput: {
    color: '#fff',
    fontSize: moderateScale(16),
    padding: moderateScale(10),
    flex: 1,
  },
  numberInput: {
    flex: 1,
    color: '#013335',
    fontSize: moderateScale(16),
    padding: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#1EB0B5',
  },
  bignumberInput: {
    color: '#013335',
    width: width - 50,
    fontSize: moderateScale(28),
    padding: moderateScale(10),
    textAlign: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#1EB0B5',
  },
  oneNumInput: {
    width: moderateScale(50),
    height: moderateScale(50),
    fontSize: moderateScale(16),
    textAlign: 'center',
    backgroundColor: 'rgba(220, 220, 220, 0.3)',
    borderRadius: moderateScale(16),
    color: '#013335',
    fontSize: moderateScale(20),
    padding: 10,
    margin: 3,
    borderColor: 'black',
  },
  oneNumInput_Border: {
    textAlign: 'center',
    flex: 1,
    fontSize: moderateScale(16),
    borderRadius: moderateScale(16),
    color: '#013335',
    fontSize: moderateScale(20),
    padding: moderateScale(10),
    borderBottomWidth: 1,
    borderBottomColor: '#1EB0B5',
  },
  error: {
    fontSize: moderateScale(10),
    color: 'red',
    textAlign: 'center',
    padding: moderateScale(10),
  },
  eye: {
    width: moderateScale(20),
    height: moderateScale(20),
    resizeMode: 'contain',
  },
});
