import {StyleSheet} from 'react-native';
import {width, height, horzontalScale, moderateScale} from './scale';

//general styles(containers ,...)
export const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    backgroundColor: '#fff',
  },
  QRContainer: {
    justifyContent: 'flex-start',
    width: width,
    alignSelf: 'center',
    alignItems: 'center',
    flex: 1,
  },
  content: {
    width: width - 50,
    alignItems: 'flex-start',
    flex: 1,
    paddingVertical: moderateScale(15),
  },
  up: {
    width: width,
    justifyContent: 'space-between',
    paddingTop: 10,
    alignItems: 'center',
  },
  topDetails: {
    width: width - 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconContainer: {
    width: moderateScale(40),
    height: moderateScale(40),
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    padding: 10,
    backgroundColor: 'rgba(255,255,255,.2)',
    borderColor: '#E5E5E5',
    borderWidth: 1,
    borderRadius: 10,
  },
  countryContainer: {
    width: width - 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: moderateScale(15),
    paddingHorizontal: moderateScale(15),
    borderRadius: 16,
  },
  topCard: {
    width: width - 50,
    height: moderateScale(150),
    backgroundColor: '#013335',
    borderTopRightRadius: moderateScale(20),
    borderTopLeftRadius: moderateScale(20),
    paddingLeft: moderateScale(20),
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  down: {
    width: width,
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  bottomCard: {
    width: width - 50,
    height: moderateScale(60),
    paddingHorizontal: moderateScale(20),
    backgroundColor: '#1DAB87',
    borderBottomRightRadius: moderateScale(20),
    borderBottomLeftRadius: moderateScale(20),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  details: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  transferContainer: {
    width: width - 50,
    backgroundColor: 'rgba(239, 243, 246, 1)',
    borderRadius: moderateScale(20),
    marginVertical: 20,
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  item: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: moderateScale(20),
  },

  viewBox: {
    justifyContent: 'center',
    width: width,
    padding: moderateScale(10),
    alignItems: 'center',
    height: moderateScale(90),
  },
  slider: {
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    height: moderateScale(140),
  },
  transactionsContainer: {
    width: width - 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  purchaseDetails: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: moderateScale(20),
  },
  itemContainer: {
    width: "100%",
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: moderateScale(10),
  },
  transContainer: {
    width: width - 50,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomColor: '#F3F4F6',
    borderBottomWidth: 2,
    paddingVertical: moderateScale(10),
  },
  simpleContainer: {
    marginVertical: moderateScale(10),
    padding: moderateScale(15),
    width: width - 50,
    borderColor: 'rgba(243, 244, 246, 1)',
    borderWidth: 1,
    borderRadius: moderateScale(10),
  },
  littleSimpleContainer: {
    marginBottom: moderateScale(15),
    padding: 15,
    width: (width - 70) / 3,
    borderColor: 'rgba(243, 244, 246, 1)',
    borderWidth: 1,
    borderRadius: moderateScale(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    padding: moderateScale(10),
    backgroundColor: '#EFF3F6',
    borderRadius: moderateScale(10),
    marginRight: moderateScale(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  editPicContainer: {
    padding: 5,
    backgroundColor: 'rgba(99, 226, 169, 1)',
    borderRadius: 100,
    margin: 1,
    position: 'absolute',
    alignSelf: 'flex-end',
    transform: [{translateY: moderateScale(65)}],
    borderColor: '#fff',
    borderWidth: 2,
  },
  transDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flex: 1,
  },
  body: {
    width: width,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  footer: {
    width: width,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    borderTopWidth: 1,
    backgroundColor: '#fff',
    borderTopColor: 'rgba(0,0,0,0.3)',
  },
  footerItem: {
    flex: 1,
    margin: moderateScale(2),
    justifyContent: 'center',
    alignItems: 'center',
  },
  scan: {
    margin: moderateScale(2),
    width: moderateScale(50),
    height: moderateScale(50),
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(29, 171, 135, 1)',
    borderRadius: moderateScale(25),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 17,
  },

  QRHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
    width: width - 50,
    marginBottom: moderateScale(10),
  },
  profileContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(20),
    borderRadius: moderateScale(16),
  },

  topLayer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: width - moderateScale(100),
    height: width - moderateScale(100),
    backgroundColor: '#fff',
    borderRadius: moderateScale(20),
    marginBottom: moderateScale(50),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 9,
    },
    shadowOpacity: 0.48,
    shadowRadius: 11.95,
    elevation: 18,
  },
  
  QRHolder: {
    justifyContent: 'center',
    alignItems: 'center',
    width: width - 150,
    height: width - 150,
    backgroundColor: '#fff',
    borderRadius: 20,
    marginTop: horzontalScale(height / 7),
  },
  ProfileBorder: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(229, 231, 235, 1)',
    borderRadius: moderateScale(200),
    padding: moderateScale(10),
    marginBottom: moderateScale(10),
    marginHorizontal: moderateScale(2),
  },
  detailBox: {
    width: '100%',
    padding: moderateScale(10),
    borderBottomColor: '#F3F4F6',
    borderBottomWidth: 1,
  },
  transferDetailsContainer: {
    width: width - 50,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: moderateScale(16),
    marginVertical: moderateScale(15),
    paddingVertical: moderateScale(20),
    paddingHorizontal: moderateScale(10),
  },
});
